[package]
name = "tufte-memo-german"
version = "0.1.2"
entrypoint = "lib.typ"
authors = ["Noah Gula", "Axel Dürkop"]
license = "MIT"
description = "A memo document template inspired by the design of Edward Tufte's books. Adapted for German i18n and with use of APA and DGP citation style."
categories = ["report"]
homepage = "https://github.com/xldrkp/tufte-memo"
repository = "https://github.com/xldrkp/tufte-memo"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"